version: '3' # composeファイルのバーション指定
services:
  # frontend
  frontend: # service名
    build: # ビルドに使用するDockerfileがあるディレクトリ指定
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    container_name: next_container
    volumes:
      - .:/frontend
    tty: true
    restart: always
