version: "3"
services:
  # backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: go_container
    # command: go run main.go
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./backend:/backend
    tty: true
    restart: always

  # database
  db:
    image: mysql:latest
    container_name: go_mysql
    environment:
      MYSQL_ROOT_PASSWORD: "yoko1893"
      MYSQL_DATABASE: "blogs"
      MYSQL_USER: "root"
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./backend/my.conf:/etc/mysql/conf.d/my.cnf
      - ./backend/mysql/:/var/lib/mysql
    ports:
      - 3306:3306
    tty: true
    restart: always
