// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"github.com/99designs/gqlgen/graphql"
)

type Node interface {
	IsNode()
}

type AuthResponse struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type BlogFilter struct {
	Title *string `json:"title"`
}

type CategoryInput struct {
	Name string `json:"name"`
}

type ImageDelete struct {
	Name string `json:"name"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type NewBlog struct {
	Image      *graphql.Upload `json:"image"`
	Title      string          `json:"title"`
	Text       string          `json:"text"`
	CategoryID string          `json:"categoryId"`
}

type NewComment struct {
	Comment string `json:"comment"`
}

type RegisterInput struct {
	Email           string `json:"email"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirmPassword"`
	FirstName       string `json:"firstName"`
	LastName        string `json:"lastName"`
}

type ResetPassword struct {
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirmPassword"`
}

type UpdateBlog struct {
	Image      *graphql.Upload `json:"image"`
	Title      *string         `json:"title"`
	Text       *string         `json:"text"`
	CategoryID string          `json:"categoryId"`
}

type UpdateUser struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
}
